#!/bin/bash
#this script will change 2 lines in the database file

sed 's/mysql.creasetoph.com/localhost/' /home/creasetoph/website/creasetoph.com/classes/Database.php > temp
rm /home/creasetoph/website/creasetoph.com/classes/Database.php
cp temp /home/creasetoph/website/creasetoph.com/classes/Database.php
rm temp
